import Foundation

// MARK: - AI-Generated Offer

/// The complete offer generated by the AI from evaluation + questionnaire answers.
/// Each position has calculated quantities, descriptions, and pricing hints.
struct GeneratedOffer: Codable {
    let title: String
    let description: String
    let servicePositions: [GeneratedServicePosition]
    let productPositions: [GeneratedProductPosition]
    let notes: String?
}

/// A fully specified service position ready for the API.
struct GeneratedServicePosition: Codable, Identifiable {
    let id: UUID
    let name: String
    let description: String
    let unitType: String
    let quantity: Double
    let netPricePerUnit: Double

    init(name: String, description: String, unitType: String, quantity: Double, netPricePerUnit: Double) {
        self.id = UUID()
        self.name = name
        self.description = description
        self.unitType = unitType
        self.quantity = quantity
        self.netPricePerUnit = netPricePerUnit
    }
}

/// A fully specified product position ready for the API.
struct GeneratedProductPosition: Codable, Identifiable {
    let id: UUID
    let name: String
    let description: String
    let unitType: String
    let quantity: Double
    let netPrice: Double
    /// If matched to catalog, the product_id from HERO
    let catalogProductId: String?

    init(name: String, description: String, unitType: String, quantity: Double, netPrice: Double, catalogProductId: String? = nil) {
        self.id = UUID()
        self.name = name
        self.description = description
        self.unitType = unitType
        self.quantity = quantity
        self.netPrice = netPrice
        self.catalogProductId = catalogProductId
    }
}
