import Foundation

// MARK: - Generated Report

/// A report generated by the AI from the recording timeline.
/// Used for both Arbeitsberichte and Baustellenberichte.
struct GeneratedReport: Codable {
    let title: String
    let summary: String
    /// Rich text sections in order. Photos/measurements are referenced inline.
    let sections: [ReportSection]
}

struct ReportSection: Codable, Identifiable {
    let id: UUID
    let heading: String
    let body: String
    /// Indices into the photos array, to embed after this section
    let photoIndices: [Int]
    /// Indices into the measurements array, to include in this section
    let measurementIndices: [Int]

    init(heading: String, body: String, photoIndices: [Int] = [], measurementIndices: [Int] = []) {
        self.id = UUID()
        self.heading = heading
        self.body = body
        self.photoIndices = photoIndices
        self.measurementIndices = measurementIndices
    }
}
